---
title: "Dashboard Design for a Varied Customer Base" 
subtitle: "NHS-R Community Conference 2023"
author: "Cancer Alliance Data Evaluation and Analysis Service (CADEAS)"
date: "`r Sys.Date()`"
output: 
  ioslides_presentation:
    widescreen: true
    logo: "./NHS_logo/NHSE.jpg"
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

-   **About CADEAS**
    -   what we do, who our stakeholders are, what kind of products we make

## The challenges

-   **Excel heavy**

    -   Historically consisted of 8 separate Excel based weekly reports
    -   Expected to be 'publication ready' within a tight timescale (around 2.5 hours) 😰😰😰

-   **Business continuity**

    -   A diverse range of stakeholders
    -   Stakeholders mostly with limited exposure to R (primarily familiar with MS Office products such as Excel and PowerPoint)

## The challenges (continued)

-   **Technical challenges**

    -   Diverse geographical interests and policy driven requirements
    -   Limited resource and time - no Shiny server hosting capacity (at least not yet)
    -   Static PowerPoint slide style products were preferred over other innovative by some\
        Limited version controls on R, R Packages and the existing R scripts - results not reproducible

## The solution

-   A Rmarkdown dashboard that is interactive, reproducible and user friendly (backward compatibility)

-   Tips on how to cater to a wide range of audiences e.g. graphs and data, very clear tips, extract in multiple formats

-   Workaround for the technical challenges

    -   A combination use of R packages such as *flexdashboard*, *crosstalk*, *plotly*, *DT* and *flextable*
    -   Minimal amount of Javascript and CSS to create an "illusion" of dependency dropdown 😵

## The solution (continued)

``` javascript
$(document).ready(function() {
    document.getElementById("PTL_TS_Primary_Selection").getElementsByClassName("selectized")[0].selectize.removeOption("");
    document.getElementById("PTL_TS_Primary_Selection").getElementsByClassName("selectized")[0].selectize.setValue("National", false);
    document.getElementById("PTL_TS_Prov_Selection").getElementsByClassName("selectized")[0].selectize.removeOption("");
    document.getElementById("PTL_TS_Regional_Selection").getElementsByClassName("selectized")[0].selectize.removeOption("");
});

var ct_filter = new crosstalk.FilterHandle('PTL_TS');
$('#PTL_TS_Primary_Selection').on("change", function() {

if(document.getElementById("PTL_TS_Primary_Selection").getElementsByClassName("selectized")[0].value == "National"){
      document.getElementById("PTL_TS_Prov_Selection").getElementsByClassName("selectized")[0].selectize.setValue(null, false);
      document.getElementById("PTL_TS_Regional_Selection").getElementsByClassName("selectized")[0].selectize.setValue(null, false);
      document.getElementById("PTL_TS_Regional_Selection").style.display = "none";
      document.getElementById("PTL_TS_Prov_Selection").style.display = "none";
} else if(...
```

## Conclusion

-   Summarise what we've said
-   Questions
